In [1]:
%matplotlib widget

In [2]:
import numpy as np
import emg3d 
import empymod as ep
import pandas as pd
from scipy.constants import mu_0
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time
import sys
sys.path.insert(1, 'src')

from Plot import grid

## Upload data and sort

In [43]:
OUT = np.load('data3D_slope10.pkl', allow_pickle=True)

In [44]:
OUT

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0  -3.00     2.0  0.012701  0.004402
1     H4   -4.0    0.0  -2.00     4.0  0.044600  0.031236
2     H8   -4.0    4.0   0.00     8.0  0.082372  0.161869
3     V2   -4.0   -2.0  -3.00     2.0  0.012284  0.002333
4     V4   -4.0    0.0  -2.00     4.0  0.049286  0.017409
..   ...    ...    ...    ...     ...       ...       ...
328   V4   32.0   36.0  34.00     4.0  0.094810  0.036363
329   V8   32.0   40.0  36.00     8.0  0.275847  0.199755
330   P2   32.0   34.1  33.05     2.1  0.027233  0.003112
331   P4   32.0   36.1  34.05     4.1  0.130151  0.034343
332   P8   32.0   40.1  36.05     8.1  0.407666  0.268840

[333 rows x 7 columns]

In [45]:
OUT_sorted = OUT.sort_values(by='geom')

In [46]:
OUT_sorted

    geom  src_x  rec_x  midpx  offset        op        ip
0     H2   -4.0   -2.0   -3.0     2.0  0.012701  0.004402
45    H2    1.0    3.0    2.0     2.0  0.012987  0.004610
297   H2   29.0   31.0   30.0     2.0  0.025296  0.009150
54    H2    2.0    4.0    3.0     2.0  0.013086  0.004672
288   H2   28.0   30.0   29.0     2.0  0.024316  0.008917
..   ...    ...    ...    ...     ...       ...       ...
59    V8    2.0   10.0    6.0     8.0  0.175555  0.120540
293   V8   28.0   36.0   32.0     8.0  0.264038  0.191926
50    V8    1.0    9.0    5.0     8.0  0.173760  0.118876
122   V8    9.0   17.0   13.0     8.0  0.192823  0.135865
266   V8   25.0   33.0   29.0     8.0  0.255705  0.184741

[333 rows x 7 columns]

In [47]:
npos = int(len(OUT_sorted)/9)

In [48]:
data_3D = np.zeros((npos-3,18))

pos=0
for p in range(-3,34):
    print(OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <p +1.06)])

    dat = np.hstack((OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['op'],
                     OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['ip'])) 
    if dat.size == 0:
        continue
    if dat.size == 18:
        data_3D[pos,:] = dat
        pos += 1
        print('pos:', pos)

   geom  src_x  rec_x  midpx  offset        op        ip
9    H2   -3.0   -1.0  -2.00     2.0  0.012734  0.004429
1    H4   -4.0    0.0  -2.00     4.0  0.044600  0.031236
15   P2   -3.0   -0.9  -1.95     2.1  0.014397  0.001002
7    P4   -4.0    0.1  -1.95     4.1  0.060748  0.012336
12   V2   -3.0   -1.0  -2.00     2.0  0.012301  0.002348
4    V4   -4.0    0.0  -2.00     4.0  0.049286  0.017409
   geom  src_x  rec_x  midpx  offset        op        ip
18   H2   -2.0    0.0  -1.00     2.0  0.012780  0.004463
10   H4   -3.0    1.0  -1.00     4.0  0.044887  0.031478
24   P2   -2.0    0.1  -0.95     2.1  0.014403  0.001002
16   P4   -3.0    1.1  -0.95     4.1  0.060873  0.012390
21   V2   -2.0    0.0  -1.00     2.0  0.012324  0.002366
13   V4   -3.0    1.0  -1.00     4.0  0.049448  0.017547
   geom  src_x  rec_x  midpx  offset        op        ip
27   H2   -1.0    1.0   0.00     2.0  0.012838  0.004503
19   H4   -2.0    2.0   0.00     4.0  0.045212  0.031754
2    H8   -4.0    4.0   0.00     8.0  0.082372  0.161869
33   P2   -1.0    1.1   0.05     2.1  0.014418  0.001007
25   P4   -2.0    2.1   0.05     4.1  0.061090  0.012493
8    P8   -4.0    4.1   0.05     8.1  0.237684  0.127216
30   V2   -1.0    1.0   0.00     2.0  0.012354  0.002388
22   V4   -2.0    2.0   0.00     4.0  0.049651  0.017706
5    V8   -4.0    4.0   0.00     8.0  0.167328  0.112475
pos: 1
   geom  src_x  rec_x  midpx  offset        op        ip
36   H2    0.0    2.0   1.00     2.0  0.012906  0.004559
28   H4   -1.0    3.0   1.00     4.0  0.045562  0.032060
11   H8   -3.0    5.0   1.00     8.0  0.082664  0.162982
42   P2    0.0    2.1   1.05     2.1  0.014443  0.001013
34   P4   -1.0    3.1   1.05     4.1  0.061388  0.012639
17   P8   -3.0    5.1   1.05     8.1  0.239400  0.128629
39   V2    0.0    2.0   1.00     2.0  0.012393  0.002413
31   V4   -1.0    3.0   1.00     4.0  0.049900  0.017888
14   V8   -3.0    5.0   1.00     8.0  0.168326  0.113536
pos: 2
   geom  src_x  rec_x  midpx  offset        op        ip
45   H2    1.0    3.0   2.00     2.0  0.012987  0.004610
37   H4    0.0    4.0   2.00     4.0  0.045968  0.032740
20   H8   -2.0    6.0   2.00     8.0  0.082730  0.164083
51   P2    1.0    3.1   2.05     2.1  0.014474  0.001024
43   P4    0.0    4.1   2.05     4.1  0.061774  0.012789
26   P8   -2.0    6.1   2.05     8.1  0.241317  0.130263
48   V2    1.0    3.0   2.00     2.0  0.012440  0.002442
40   V4    0.0    4.0   2.00     4.0  0.050199  0.018096
23   V8   -2.0    6.0   2.00     8.0  0.169451  0.114692
pos: 3
   geom  src_x  rec_x  midpx  offset        op        ip
54   H2    2.0    4.0   3.00     2.0  0.013086  0.004672
46   H4    1.0    5.0   3.00     4.0  0.046425  0.033124
29   H8   -1.0    7.0   3.00     8.0  0.082633  0.165185
60   P2    2.0    4.1   3.05     2.1  0.014509  0.001036
52   P4    1.0    5.1   3.05     4.1  0.062197  0.012993
35   P8   -1.0    7.1   3.05     8.1  0.243406  0.132092
57   V2    2.0    4.0   3.00     2.0  0.012496  0.002475
49   V4    1.0    5.0   3.00     4.0  0.050552  0.018332
32   V8   -1.0    7.0   3.00     8.0  0.170718  0.115960
pos: 4
   geom  src_x  rec_x  midpx  offset        op        ip
63   H2    3.0    5.0   4.00     2.0  0.013204  0.004742
55   H4    2.0    6.0   4.00     4.0  0.046968  0.033549
38   H8    0.0    8.0   4.00     8.0  0.082696  0.169410
69   P2    3.0    5.1   4.05     2.1  0.014550  0.001051
61   P4    2.0    6.1   4.05     4.1  0.062685  0.013222
44   P8    0.0    8.1   4.05     8.1  0.246346  0.134614
66   V2    3.0    5.0   4.00     2.0  0.012562  0.002512
58   V4    2.0    6.0   4.00     4.0  0.050962  0.018597
41   V8    0.0    8.0   4.00     8.0  0.172150  0.117351
pos: 5
   geom  src_x  rec_x  midpx  offset        op        ip
72   H2    4.0    6.0   5.00     2.0  0.013339  0.004819
64   H4    3.0    7.0   5.00     4.0  0.047598  0.034031
47   H8    1.0    9.0   5.00     8.0  0.082584  0.170676
78   P2    4.0    6.1   5.05     2.1  0.014600  0.001067
70   P4    3.0    7.1   5.05     4.1  0.063246  0.013475
53   P8    1.0    9.1   5.05     8.1  0.248876  0.136821
75   V2    4.0    6.0   5.00     2.0  0.012637  0.002554
67   V4    3.0    7.0   5.00     4.0  0.051428  0.018891
50   V8    1.0    9.0   5.00     8.0  0.173760  0.118876
pos: 6
   geom  src_x  rec_x  midpx  offset        op        ip
81   H2    5.0    7.0   6.00     2.0  0.013490  0.004907
73   H4    4.0    8.0   6.00     4.0  0.048308  0.034582
56   H8    2.0   10.0   6.00     8.0  0.082562  0.172121
87   P2    5.0    7.1   6.05     2.1  0.014658  0.001085
79   P4    4.0    8.1   6.05     4.1  0.063887  0.013757
62   P8    2.0   10.1   6.05     8.1  0.251699  0.139229
84   V2    5.0    7.0   6.00     2.0  0.012721  0.002599
76   V4    4.0    8.0   6.00     4.0  0.051950  0.019213
59   V8    2.0   10.0   6.00     8.0  0.175555  0.120540
pos: 7
   geom  src_x  rec_x  midpx  offset        op        ip
90   H2    6.0    8.0   7.00     2.0  0.013658  0.005004
82   H4    5.0    9.0   7.00     4.0  0.049088  0.035182
65   H8    3.0   11.0   7.00     8.0  0.082625  0.173789
96   P2    6.0    8.1   7.05     2.1  0.014725  0.001106
88   P4    5.0    9.1   7.05     4.1  0.064607  0.014066
71   P8    3.0   11.1   7.05     8.1  0.254843  0.141836
93   V2    6.0    8.0   7.00     2.0  0.012814  0.002649
85   V4    5.0    9.0   7.00     4.0  0.052525  0.019563
68   V8    3.0   11.0   7.00     8.0  0.177531  0.122344
pos: 8
    geom  src_x  rec_x  midpx  offset        op        ip
99    H2    7.0    9.0   8.00     2.0  0.013841  0.005106
91    H4    6.0   10.0   8.00     4.0  0.049931  0.035826
74    H8    4.0   12.0   8.00     8.0  0.082737  0.175704
105   P2    7.0    9.1   8.05     2.1  0.014802  0.001129
97    P4    6.0   10.1   8.05     4.1  0.065407  0.014399
80    P8    4.0   12.1   8.05     8.1  0.258310  0.144641
102   V2    7.0    9.0   8.00     2.0  0.012917  0.002703
94    V4    6.0   10.0   8.00     4.0  0.053153  0.019941
77    V8    4.0   12.0   8.00     8.0  0.179680  0.124287
pos: 9
    geom  src_x  rec_x  midpx  offset        op        ip
108   H2    8.0   10.0   9.00     2.0  0.014040  0.005216
100   H4    7.0   11.0   9.00     4.0  0.050835  0.036523
83    H8    5.0   13.0   9.00     8.0  0.082867  0.177786
114   P2    8.0   10.1   9.05     2.1  0.014889  0.001154
106   P4    7.0   11.1   9.05     4.1  0.066290  0.014759
89    P8    5.0   13.1   9.05     8.1  0.262066  0.147635
111   V2    8.0   10.0   9.00     2.0  0.013029  0.002760
103   V4    7.0   11.0   9.00     4.0  0.053837  0.020345
86    V8    5.0   13.0   9.00     8.0  0.181995  0.126363
pos: 10
    geom  src_x  rec_x  midpx  offset        op        ip
117   H2    9.0   11.0  10.00     2.0  0.014256  0.005334
109   H4    8.0   12.0  10.00     4.0  0.051797  0.037257
92    H8    6.0   14.0  10.00     8.0  0.082975  0.179978
123   P2    9.0   11.1  10.05     2.1  0.014985  0.001182
115   P4    8.0   12.1  10.05     4.1  0.067255  0.015148
98    P8    6.0   14.1  10.05     8.1  0.266087  0.150814
120   V2    9.0   11.0  10.00     2.0  0.013151  0.002821
112   V4    8.0   12.0  10.00     4.0  0.054576  0.020774
95    V8    6.0   14.0  10.00     8.0  0.184469  0.128567
pos: 11
    geom  src_x  rec_x  midpx  offset        op        ip
126   H2   10.0   12.0  11.00     2.0  0.014489  0.005456
118   H4    9.0   13.0  11.00     4.0  0.052815  0.038019
101   H8    7.0   15.0  11.00     8.0  0.083041  0.182301
132   P2   10.0   12.1  11.05     2.1  0.015093  0.001214
124   P4    9.0   13.1  11.05     4.1  0.068306  0.015565
107   P8    7.0   15.1  11.05     8.1  0.270363  0.154189
129   V2   10.0   12.0  11.00     2.0  0.013284  0.002885
121   V4    9.0   13.0  11.00     4.0  0.055373  0.021227
104   V8    7.0   15.0  11.00     8.0  0.187100  0.130890
pos: 12
    geom  src_x  rec_x  midpx  offset        op        ip
135   H2   11.0   13.0  12.00     2.0  0.014741  0.005585
127   H4   10.0   14.0  12.00     4.0  0.053884  0.038826
110   H8    8.0   16.0  12.00     8.0  0.083017  0.184719
141   P2   11.0   13.1  12.05     2.1  0.015213  0.001248
133   P4   10.0   14.1  12.05     4.1  0.069451  0.016014
116   P8    8.0   16.1  12.05     8.1  0.274871  0.157760
138   V2   11.0   13.0  12.00     2.0  0.013430  0.002954
130   V4   10.0   14.0  12.00     4.0  0.056232  0.021705
113   V8    8.0   16.0  12.00     8.0  0.189884  0.133325
pos: 13
    geom  src_x  rec_x  midpx  offset        op        ip
144   H2   12.0   14.0  13.00     2.0  0.015013  0.005723
136   H4   11.0   15.0  13.00     4.0  0.055007  0.039673
119   H8    9.0   17.0  13.00     8.0  0.082892  0.187206
150   P2   12.0   14.1  13.05     2.1  0.015347  0.001285
142   P4   11.0   15.1  13.05     4.1  0.070693  0.016495
125   P8    9.0   17.1  13.05     8.1  0.279595  0.161517
147   V2   12.0   14.0  13.00     2.0  0.013588  0.003026
139   V4   11.0   15.0  13.00     4.0  0.057157  0.022206
122   V8    9.0   17.0  13.00     8.0  0.192823  0.135865
pos: 14
    geom  src_x  rec_x  midpx  offset        op        ip
153   H2   13.0   15.0  14.00     2.0  0.015308  0.005865
145   H4   12.0   16.0  14.00     4.0  0.056181  0.040542
128   H8   10.0   18.0  14.00     8.0  0.082620  0.189780
159   P2   13.0   15.1  14.05     2.1  0.015497  0.001326
151   P4   12.0   16.1  14.05     4.1  0.072043  0.017004
134   P8   10.0   18.1  14.05     8.1  0.284540  0.165445
156   V2   13.0   15.0  14.00     2.0  0.013760  0.003101
148   V4   12.0   16.0  14.00     4.0  0.058151  0.022732
131   V8   10.0   18.0  14.00     8.0  0.195916  0.138509
pos: 15
    geom  src_x  rec_x  midpx  offset        op        ip
162   H2   14.0   16.0  15.00     2.0  0.015626  0.006014
154   H4   13.0   17.0  15.00     4.0  0.057417  0.041452
137   H8   11.0   19.0  15.00     8.0  0.082236  0.192438
168   P2   14.0   16.1  15.05     2.1  0.015665  0.001370
160   P4   13.0   17.1  15.05     4.1  0.073511  0.017544
143   P8   11.0   19.1  15.05     8.1  0.289703  0.169543
165   V2   14.0   16.0  15.00     2.0  0.013948  0.003181
157   V4   13.0   17.0  15.00     4.0  0.059221  0.023282
140   V8   11.0   19.0  15.00     8.0  0.199167  0.141254
pos: 16
    geom  src_x  rec_x  midpx  offset        op        ip
171   H2   15.0   17.0  16.00     2.0  0.015973  0.006172
163   H4   14.0   18.0  16.00     4.0  0.058707  0.042401
146   H8   12.0   20.0  16.00     8.0  0.081688  0.195086
177   P2   15.0   17.1  16.05     2.1  0.015854  0.001417
169   P4   14.0   18.1  16.05     4.1  0.075110  0.018119
152   P8   12.0   20.1  16.05     8.1  0.295076  0.173798
174   V2   15.0   17.0  16.00     2.0  0.014154  0.003264
166   V4   14.0   18.0  16.00     4.0  0.060372  0.023856
149   V8   12.0   20.0  16.00     8.0  0.202578  0.144095
pos: 17
    geom  src_x  rec_x  midpx  offset        op        ip
180   H2   16.0   18.0  17.00     2.0  0.016348  0.006336
172   H4   15.0   19.0  17.00     4.0  0.060066  0.043374
155   H8   13.0   21.0  17.00     8.0  0.081042  0.197785
186   P2   16.0   18.1  17.05     2.1  0.016066  0.001469
178   P4   15.0   19.1  17.05     4.1  0.076845  0.018734
161   P8   13.0   21.1  17.05     8.1  0.300673  0.178247
183   V2   16.0   18.0  17.00     2.0  0.014379  0.003351
175   V4   15.0   19.0  17.00     4.0  0.061611  0.024456
158   V8   13.0   21.0  17.00     8.0  0.206156  0.147029
pos: 18
    geom  src_x  rec_x  midpx  offset        op        ip
189   H2   17.0   19.0  18.00     2.0  0.016758  0.006506
181   H4   16.0   20.0  18.00     4.0  0.061470  0.044384
164   H8   14.0   22.0  18.00     8.0  0.080179  0.200519
195   P2   17.0   19.1  18.05     2.1  0.016303  0.001526
187   P4   16.0   20.1  18.05     4.1  0.078733  0.019388
170   P8   14.0   22.1  18.05     8.1  0.306502  0.182904
192   V2   17.0   19.0  18.00     2.0  0.014626  0.003443
184   V4   16.0   20.0  18.00     4.0  0.062944  0.025080
167   V8   14.0   22.0  18.00     8.0  0.209898  0.150049
pos: 19
    geom  src_x  rec_x  midpx  offset        op        ip
198   H2   18.0   20.0  19.00     2.0  0.017200  0.006687
190   H4   17.0   21.0  19.00     4.0  0.062942  0.045443
173   H8   15.0   23.0  19.00     8.0  0.079192  0.203289
204   P2   18.0   20.1  19.05     2.1  0.016573  0.001587
196   P4   17.0   21.1  19.05     4.1  0.080780  0.020088
179   P8   15.0   23.1  19.05     8.1  0.312538  0.187783
201   V2   18.0   20.0  19.00     2.0  0.014897  0.003539
193   V4   17.0   21.0  19.00     4.0  0.064380  0.025730
176   V8   15.0   23.0  19.00     8.0  0.213813  0.153149
pos: 20
    geom  src_x  rec_x  midpx  offset        op        ip
207   H2   19.0   21.0  20.00     2.0  0.017684  0.006876
199   H4   18.0   22.0  20.00     4.0  0.064441  0.046523
182   H8   16.0   24.0  20.00     8.0  0.077878  0.206040
213   P2   19.0   21.1  20.05     2.1  0.016876  0.001653
205   P4   18.0   22.1  20.05     4.1  0.083009  0.020827
188   P8   16.0   24.1  20.05     8.1  0.318804  0.192857
210   V2   19.0   21.0  20.00     2.0  0.015196  0.003640
202   V4   18.0   22.0  20.00     4.0  0.065923  0.026405
185   V8   16.0   24.0  20.00     8.0  0.217889  0.156323
pos: 21
    geom  src_x  rec_x  midpx  offset        op        ip
216   H2   20.0   22.0  21.00     2.0  0.018206  0.007070
208   H4   19.0   23.0  21.00     4.0  0.066017  0.047641
191   H8   17.0   25.0  21.00     8.0  0.076465  0.208881
222   P2   20.0   22.1  21.05     2.1  0.017223  0.001723
214   P4   19.0   23.1  21.05     4.1  0.085418  0.021612
197   P8   17.0   25.1  21.05     8.1  0.325300  0.198160
219   V2   20.0   22.0  21.00     2.0  0.015524  0.003745
211   V4   19.0   23.0  21.00     4.0  0.067587  0.027106
194   V8   17.0   25.0  21.00     8.0  0.222134  0.159565
pos: 22
    geom  src_x  rec_x  midpx  offset        op        ip
225   H2   21.0   23.0  22.00     2.0  0.018782  0.007276
217   H4   20.0   24.0  22.00     4.0  0.067596  0.048793
200   H8   18.0   26.0  22.00     8.0  0.074609  0.211575
231   P2   21.0   23.1  22.05     2.1  0.017613  0.001800
223   P4   20.0   24.1  22.05     4.1  0.088052  0.022441
206   P8   18.0   26.1  22.05     8.1  0.332044  0.203653
228   V2   21.0   23.0  22.00     2.0  0.015888  0.003855
220   V4   20.0   24.0  22.00     4.0  0.069373  0.027832
203   V8   18.0   26.0  22.00     8.0  0.226517  0.162860
pos: 23
    geom  src_x  rec_x  midpx  offset        op        ip
234   H2   22.0   24.0  23.00     2.0  0.019399  0.007490
226   H4   21.0   25.0  23.00     4.0  0.069264  0.049975
209   H8   19.0   27.0  23.00     8.0  0.072724  0.214280
240   P2   22.0   24.1  23.05     2.1  0.018067  0.001884
232   P4   21.0   25.1  23.05     4.1  0.090891  0.023331
215   P8   19.0   27.1  23.05     8.1  0.339015  0.209406
237   V2   22.0   24.0  23.00     2.0  0.016290  0.003969
229   V4   21.0   25.0  23.00     4.0  0.071296  0.028583
212   V8   19.0   27.0  23.00     8.0  0.231047  0.166194
pos: 24
    geom  src_x  rec_x  midpx  offset        op        ip
243   H2   23.0   25.0  24.00     2.0  0.020085  0.007712
235   H4   22.0   26.0  24.00     4.0  0.070877  0.051167
218   H8   20.0   28.0  24.00     8.0  0.070149  0.216725
249   P2   23.0   25.1  24.05     2.1  0.018576  0.001978
241   P4   22.0   26.1  24.05     4.1  0.094011  0.024280
224   P8   20.0   28.1  24.05     8.1  0.346304  0.215405
246   V2   23.0   25.0  24.00     2.0  0.016737  0.004089
238   V4   22.0   26.0  24.00     4.0  0.073352  0.029356
221   V8   20.0   28.0  24.00     8.0  0.235645  0.169534
pos: 25
    geom  src_x  rec_x  midpx  offset        op        ip
252   H2   24.0   26.0  25.00     2.0  0.020810  0.007943
244   H4   23.0   27.0  25.00     4.0  0.072584  0.052403
227   H8   21.0   29.0  25.00     8.0  0.067578  0.219154
258   P2   24.0   26.1  25.05     2.1  0.019180  0.002079
250   P4   23.0   27.1  25.05     4.1  0.097359  0.025308
233   P8   21.0   29.1  25.05     8.1  0.353851  0.221749
255   V2   24.0   26.0  25.00     2.0  0.017231  0.004213
247   V4   23.0   27.0  25.00     4.0  0.075560  0.030148
230   V8   21.0   29.0  25.00     8.0  0.240300  0.172856
pos: 26
    geom  src_x  rec_x  midpx  offset        op        ip
261   H2   25.0   27.0  26.00     2.0  0.021620  0.008183
253   H4   24.0   28.0  26.00     4.0  0.074116  0.053623
236   H8   22.0   30.0  26.00     8.0  0.063695  0.220944
267   P2   25.0   27.1  26.05     2.1  0.019852  0.002193
259   P4   24.0   28.1  26.05     4.1  0.101069  0.026402
242   P8   22.0   30.1  26.05     8.1  0.361823  0.228344
264   V2   25.0   27.0  26.00     2.0  0.017782  0.004342
256   V4   24.0   28.0  26.00     4.0  0.077896  0.030953
239   V8   22.0   30.0  26.00     8.0  0.244818  0.176093
pos: 27
    geom  src_x  rec_x  midpx  offset        op        ip
270   H2   26.0   28.0  27.00     2.0  0.022459  0.008426
262   H4   25.0   29.0  27.00     4.0  0.075739  0.054846
245   H8   23.0   31.0  27.00     8.0  0.059581  0.222538
276   P2   26.0   28.1  27.05     2.1  0.020673  0.002316
268   P4   25.0   29.1  27.05     4.1  0.105027  0.027587
251   P8   23.0   31.1  27.05     8.1  0.370043  0.235225
273   V2   26.0   28.0  27.00     2.0  0.018389  0.004474
265   V4   25.0   29.0  27.00     4.0  0.080373  0.031766
248   V8   23.0   31.0  27.00     8.0  0.249113  0.179204
pos: 28
    geom  src_x  rec_x  midpx  offset        op        ip
279   H2   27.0   29.0  28.00     2.0  0.023398  0.008674
271   H4   26.0   30.0  28.00     4.0  0.076926  0.055988
254   H8   24.0   32.0  28.00     8.0  0.052280  0.222557
285   P2   27.0   29.1  28.05     2.1  0.021579  0.002456
277   P4   26.0   30.1  28.05     4.1  0.109494  0.028835
260   P8   24.0   32.1  28.05     8.1  0.378247  0.241892
282   V2   27.0   29.0  28.00     2.0  0.019066  0.004608
274   V4   26.0   30.0  28.00     4.0  0.082914  0.032571
257   V8   24.0   32.0  28.00     8.0  0.252729  0.182083
pos: 29
    geom  src_x  rec_x  midpx  offset        op        ip
288   H2   28.0   30.0  29.00     2.0  0.024316  0.008917
280   H4   27.0   31.0  29.00     4.0  0.078049  0.057073
263   H8   25.0   33.0  29.00     8.0  0.043934  0.222030
294   P2   28.0   30.1  29.05     2.1  0.022726  0.002605
286   P4   27.0   31.1  29.05     4.1  0.114198  0.030180
269   P8   25.0   33.1  29.05     8.1  0.382623  0.246876
291   V2   28.0   30.0  29.00     2.0  0.019797  0.004742
283   V4   27.0   31.0  29.00     4.0  0.085485  0.033353
266   V8   25.0   33.0  29.00     8.0  0.255705  0.184741
pos: 30
    geom  src_x  rec_x  midpx  offset        op        ip
297   H2   29.0   31.0  30.00     2.0  0.025296  0.009150
289   H4   28.0   32.0  30.00     4.0  0.077771  0.057852
272   H8   26.0   34.0  30.00     8.0  0.037333  0.222121
303   P2   29.0   31.1  30.05     2.1  0.023972  0.002775
295   P4   28.0   32.1  30.05     4.1  0.119386  0.031496
278   P8   26.0   34.1  30.05     8.1  0.385573  0.251072
300   V2   29.0   31.0  30.00     2.0  0.020583  0.004874
292   V4   28.0   32.0  30.00     4.0  0.087813  0.034081
275   V8   26.0   34.0  30.00     8.0  0.258478  0.187256
pos: 31
    geom  src_x  rec_x  midpx  offset        op        ip
306   H2   30.0   32.0  31.00     2.0  0.025979  0.009345
298   H4   29.0   33.0  31.00     4.0  0.076549  0.058469
281   H8   27.0   35.0  31.00     8.0  0.032022  0.222549
312   P2   30.0   32.1  31.05     2.1  0.025570  0.002937
304   P4   29.0   33.1  31.05     4.1  0.122583  0.032498
287   P8   27.0   35.1  31.05     8.1  0.387652  0.254831
309   V2   30.0   32.0  31.00     2.0  0.021337  0.004995
301   V4   29.0   33.0  31.00     4.0  0.089765  0.034741
284   V8   27.0   35.0  31.00     8.0  0.261217  0.189645
pos: 32
    geom  src_x  rec_x  midpx  offset        op        ip
315   H2   31.0   33.0  32.00     2.0  0.026262  0.009499
307   H4   30.0   34.0  32.00     4.0  0.076553  0.059229
290   H8   28.0   36.0  32.00     8.0  0.028604  0.223575
321   P2   31.0   33.1  32.05     2.1  0.026480  0.003058
313   P4   30.0   34.1  32.05     4.1  0.125200  0.033277
296   P8   28.0   36.1  32.05     8.1  0.390237  0.258319
318   V2   31.0   33.0  32.00     2.0  0.021955  0.005102

In [49]:
np.save('data_3D_slope10_sorted', data_3D[1:33])